### PR TITLE
refactor: ♻️ Nate being picky and changing things he doesn't like

### PR DESCRIPTION
**Pull request by nstringham**
@coxender

### CODE REVIEW

**Review by coxender — CHANGES_REQUESTED** [review]
This code does not work as intended.

It is expected that the user can submit a file format that the bot specifies and execute the command without error.

When giving a file for channelparse.csv, the bot specifies to not use an extension and exits.
If a file is given without an extension as the bot specifies, the execution of the command crashes.

**Comment by nstringham** [comment]
> This code does not work as intended.
> 
> It is expected that the user can submit a file format that the bot specifies and execute the command without error.
> 
> When giving a file for channelparse.csv, the bot specifies to not use an extension and exits. If a file is given without an extension as the bot specifies, the execution of the command crashes.

Is this a regression?

**Comment by coxender** [comment]
> Is this a regression?

Yes

**Comment by coxender** [comment]
@nstringham  This should fix the issues it was causing: https://github.com/nstringham/CompsciBot/pull/1

**Comment by nstringham** [comment]
I really wish we had tests in this project

**Pull request merged**
