### PR TITLE
feat: ✨ make class roles mentionable by everyone

### PR DESCRIPTION
**Pull request by nstringham**
@Nanosplitter asked if we can make class roles mentionable.

I am not sure if that is a good idea but if that is something we want to do then here is the code.

### CODE REVIEW

**Comment by coxender** [comment]
Dang, too late for this

**Comment by nstringham** [comment]
> Dang, too late for this

I mean you're still more than welcome to tell me I'm an idiot. I'll gladly fix it for you

**Comment by coxender** [comment]
I think mentioning roles is a bad idea, mostly because they are per class not per section, so other sections will get notified.

**Comment by nstringham** [comment]
> I think mentioning roles is a bad idea, mostly because they are per class not per section, so other sections will get notified.

That's a good point.

I think the intended use case is someone wanting to send a notification to everyone in there class can you think of a different way of accomplishing this?

I wonder what percent of people mute the sections they are not a part of?

**Comment by coxender** [comment]
I guess the issue is, if it's muted will the role notifications still ping them?  If  it does can we configure that at the role level? Or even the channel/section level?

**Comment by nstringham** [comment]
Muting will disabled all notifications for a channel including mentions

**Comment by nstringham** [comment]
Ok I was looking at other options and here's an alternative to consider:

We allow people to do @everyone and @here within the class channels. (This permission also allows people mention any role within that channel)

The advantage is that it forces people to use the channels so they don't ping people from other sections by accident and I suspect using @everyone will be more intuitive for some people.

The disadvantage is that it might ping the Admins because they have read access to all channels

**Comment by nstringham** [comment]
I made #57 to implement the idea of using @everyone instead

**Pull request merged**
